function animate_drone(Y, params)
% Animation of the drone flying around an obstacle.

figure('Name','Drone Flight Animation',...
       'NumberTitle','off',...
       'Position',[120 80 1000 650]);

hold on
grid on
grid minor
box on
axis equal

xlabel('x Position (m)')
ylabel('y Position (m)')
title('Drone Flight Animation')

%% Obstacle 

theta = linspace(0,2*pi,200);

plot(150 + 20*cos(theta),...
     -70 + 20*sin(theta),...
     'k','LineWidth',2);

plot(150,-70,...
    'ko',...
    'MarkerFaceColor','k',...
    'MarkerSize',8);

text(153,-68,...
    'Obstacle',...
    'FontWeight','bold');

%% Planned Path 

plot(Y(1,:),Y(2,:),...
    '--',...
    'Color',[0.75 0.75 0.75],...
    'LineWidth',1.5);

%% Start & Finish 

plot(Y(1,1),Y(2,1),...
    'gs',...
    'MarkerFaceColor','g',...
    'MarkerSize',8);

text(Y(1,1)+5,...
     Y(2,1)-2,...
     'Start',...
     'FontWeight','bold');

plot(Y(1,end),Y(2,end),...
    'rs',...
    'MarkerFaceColor','r',...
    'MarkerSize',8);

text(Y(1,end)-18,...
     Y(2,end)-8,...
     'Finish',...
     'FontWeight','bold');

%% Axis Limits

xlim([0 max(Y(1,:))+20])
ylim([min(Y(2,:))-20 20])

%% Flight Trail

trail = animatedline(...
    'Color','b',...
    'LineWidth',2);

%% Drone 

L = 5;

% Horizontal arm
arm1 = plot([0 0],[0 0],...
    'r','LineWidth',2);

% Vertical arm
arm2 = plot([0 0],[0 0],...
    'r','LineWidth',2);

% Drone body
body = plot(0,0,...
    'ko',...
    'MarkerFaceColor','y',...
    'MarkerSize',9);

%% Time Display
timeText = text(10,16,...
    'Time = 0.0 s',...
    'FontSize',12,...
    'FontWeight','bold',...
    'BackgroundColor','white');

%% Animation 

for k = 1:length(Y)

    x = Y(1,k);
    y = Y(2,k);

    % Update trail
    addpoints(trail,x,y);

    % Horizontal arm
    set(arm1,...
        'XData',[x-L x+L],...
        'YData',[y y]);

    % Vertical arm
    set(arm2,...
        'XData',[x x],...
        'YData',[y-L y+L]);

    % Drone body
    set(body,...
        'XData',x,...
        'YData',y);

    % Update time
    set(timeText,...
        'String',sprintf('Time = %.1f s',(k-1)*params.h));

    drawnow

    pause(0.01)

end

end